apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: farm
  name: lab-deployment
  namespace: default
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 20
  replicas: 1
  selector:
    matchLabels:
      app: farm
  template:
    metadata:
      labels:
        app: farm
      namespace: default
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-setup
        - configMapRef:
            name: feature-toggles
        image: harbor.dev.afsmtddso.com/devsecops-lab/lab:b169b26-d1e0479
        name: farm
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: farm
  name: lab-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: farm
