apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: farm
  name: lab-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm
  template:
    metadata:
      labels:
        app: farm
      namespace: default
    spec:
      containers:
      - env:
        - name: DB_USER
          value: "$(DB_USER)"
        - name: DB_PASS
          value: "$(DB_PASS)"
        image: harbor.dev.afsmtddso.com/devsecops-lab/lab@sha256:edbcefb169126a463b967cdcd814f622edfade527723bb9f664052330a1a330d
        name: farm
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: farm
  name: lab-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: farm