apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
      namespace: default
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-setup
              key: DB_PASS
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-setup
              key: DB_NAME
        image: harbor.dev.afsmtddso.com/devsecops-lab/db@sha256:5c3923c5fba0ef853735ee1f724de34ced2a89dce8486a48a31e0af4f4f8376c
        imagePullPolicy: Always
        name: db
        ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: db