apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
      namespace: default
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: "$(DB_PASS)"
        - name: POSTGRES_DB
          value: "$(DB_NAME)"
        image: harbor.dev.afsmtddso.com/devsecops-lab/db@sha256:5c10798d0bf3ab59308180dc9d002454157f7c941bdddbf8973bd3a7e8c8662a
        imagePullPolicy: Always
        name: db
        ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: db