apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: DevSecOps-Labs-Cluster
  region: us-east-2
  version: "1.22"

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.large
    minSize: 1
    maxSize: 4
    desiredCapacity: 4
    volumeSize: 16
