apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instructor-clusterrole
rules:
- apiGroups: ["apps"]
  resources: ["ResourceAll"]
  verbs: ["VerbAll"]
- apiGroups: [""]
  resources: ["ResourceAll"]
  verbs: ["VerbAll"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["deployments", "pods", "replicasets", "events"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["deployments", "pods", "pods/log"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets", "services", "configmaps"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- nonResourceURLs: ["/api/*", "/metrics"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instructor-clusterrole-binding
subjects:
- kind: Group
  name: instructor-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: instructor-clusterrole
  apiGroup: rbac.authorization.k8s.io
